### ISSUE TITLE
Better handling of /etc/libvirt/qemu.conf configuration file

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1151]
---

Author Name: **Maciej Delmanowski** (Maciej Delmanowski)
Original Redmine Issue: 4947, https://dev.opennebula.org/issues/4947
Original Date: 2016-12-01

---

The <code>openebula-node</code> Debian package does not handle the <code>/etc/libvirt/qemu.conf</code> configuration file in a sane way. There are two issues:

* The <code>opennebula-node</code> postinst script checks the existence of the <code>qemu.conf</code> configuration file, and if it finds one, the existing configuration file is moved out of the way and replaced by a stub configuration file with minimum set of configuration options required by OpenNebula. This completely destroys existing configuration created by the local system administrator, without confirmation.

* The <code>/etc/libvirt/qemu.conf</code> configuration file, in Debian Jessie, is managed by the <code>libvirt-qemu-system</code> package and is marked as a Conffile. After the <code>opennebula-node</code> package changes the existing configuration file, future <code>libvirt-qemu-system</code> package upgrades might be interrupted by the <code>debconf</code> system asking the user what to do with the changed configuration file.

The above issues affect automated installation and management of OpenNebula nodes to the point, where potential users (me included) might drop the usage of the <code>opennebula-node</code> package completely and just apply the required changes using their configuration management system of choice. Therefore I think that the current <code>postinst</code> script included in the package should be fixed. Suggested solutions:

* Check if the <code>/etc/libvirt/qemu.conf</code> configuration file contains the desired configuration (user/group/dynamic_ownership) before blindly overwriting it.

* If the script decides to write the new configuration file with the required changes, don't overwrite the <code>/etc/libvirt/qemu.conf</code> configuration file directly. Instead, check potential diversions using the <code>dpkg-divert</code> command and operate on that. If there are no diversions, create a diversion before writing the new configuration - this will ensure that upgrades of the <code>libvirt-qemu-system</code> package work correctly.

**Comment by vholer** [comment]
This has been fixed by https://github.com/OpenNebula/one/issues/1768, Libvirt configuration is now managed by the Augeas. It's not replaced as a whole, but only modifies the particular parameters. Closing as fixed.

Note about the:
> future libvirt-qemu-system package upgrades might be interrupted by the debconf system asking the user what to do with the changed configuration file.

If you are running `apt-get` non-interactively, you also need to instruct the `apt-get` to use the non-interactive interface (via env. variable `DEBIAN_FRONTEND=noninteractive`), and how to deal with the configuration file changes (via parametrs `--force-confnew`, `--force-confold`, `--force-confdef`). Please check:

* https://debian-handbook.info/browse/stable/sect.automatic-upgrades.html
* https://debian-handbook.info/browse/stable/sect.package-meta-information.html#sidebar.questions-conffiles
