### ISSUE TITLE
VM Group "soft" affinity / anti affinity rules

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1318]
---

Author Name: **elder one** (elder one)
Original Redmine Issue: 5361, https://dev.opennebula.org/issues/5361
Original Date: 2017-09-12

---

In some situations is better to run VM anywhere than have it in pending state due to insufficient placement rules.
For example on hardware failure, VM-s tied to failed host with VM group affinity rules wouldn't boot on another host.

So having a "soft" parameter that tries to meet rules defined, but when impossible condition is met, writes warning to log and continues with next best possible outcome.

**Comment by tkald** [comment]
Still needed ...

**Comment by rsmontero** [comment]
I may be wrong, but:
1. If the host fails, that would trigger the FT hook. That would restart the VMs in other host
2. Pending VMs will follow the new placement of other VMs in the group
3. When no FT hook is defined, the affinity policies are indeed soft. If a VM (in that group) is deployed in another host that would be a valid host. 
4. If there is no hook I assume that the admin wants to be notified of this error conditions and recover them manually (e.g. moving failed VMs to another host, or manually deploy one of the pending VMs). In any case, the current affinity policies will recover, as I said they actually implement a soft condition.

Are we missing something here?

**Comment by tkald** [comment]
When I set vm group affinity to only 2 hosts and 2 vm group roles anti-affined, VM on failed host won't boot. 

```
onevmgroup show 3
VM GROUP 3 INFORMATION
ID             : 3
NAME           : testgroup
USER           : oneadmin
GROUP          : oneadmin
LOCK           : None
PERMISSIONS

OWNER          : um-
GROUP          : ---
OTHER          : ---

ROLES
ID   NAME     POLICY       AFFINED_HOSTS      ANTI_AFFINED_HOST  VIRTUAL_MACHINES
0    front1   ANTI_AFFINED 1, 6               -                  4129
1    front2   ANTI_AFFINED 1, 6               -                  4130

```

Now I also discovered that even after successful fencing when "failed" host comes online, VM in UNKNOWN state won't be resheduled to that only possible host. 

Simulated host failure:
```
tail -f /var/log/one/host_error.log
[2019-03-13 17:59:38 +0200][HOST 1][I] Hook launched
[2019-03-13 17:59:38 +0200][HOST 1][I] hostname: vml-vm1
[2019-03-13 17:59:38 +0200][HOST 1][I] Wait 13 cycles.
[2019-03-13 17:59:38 +0200][HOST 1][I] Sleeping 390 seconds.
[2019-03-13 18:06:08 +0200][HOST 1][I] Fencing enabled
[2019-03-13 18:06:17 +0200][HOST 1][I] Success: Rebooted
[2019-03-13 18:06:17 +0200][HOST 1][I] Fencing success
[2019-03-13 18:06:17 +0200][HOST 1][I] states: 3, 5, 8
[2019-03-13 18:06:17 +0200][HOST 1][I] vms: ["4129"]
[2019-03-13 18:06:17 +0200][HOST 1][I] resched 4129
[2019-03-13 18:06:17 +0200][HOST 1][I] Hook finished
```
After that host gets online but scheduler won't reschedule VM to the same host:

```
tail -f /var/log/one/sched.log
Wed Mar 13 18:32:59 2019 [Z0][VM][D]: Found 1 pending/rescheduling VMs.
Wed Mar 13 18:32:59 2019 [Z0][HOST][D]: Discovered 3 enabled hosts.
Wed Mar 13 18:32:59 2019 [Z0][VM][D]: VMs in VMGroups:

Wed Mar 13 18:32:59 2019 [Z0][VNET][D]: Discovered 61 vnets.
Wed Mar 13 18:32:59 2019 [Z0][SCHED][D]: Match-making results for VM 4129:
        Cannot schedule VM, there is no suitable host.
```

Also if there's real host failure, lets say power failure - fencing will fail and VMs on that host will not be rescheduled.

```
[2019-03-13 15:15:57 +0200][HOST 1][I] Hook launched
[2019-03-13 15:15:57 +0200][HOST 1][I] hostname: vml-vm1
[2019-03-13 15:15:57 +0200][HOST 1][I] Wait 13 cycles.
[2019-03-13 15:15:57 +0200][HOST 1][I] Sleeping 390 seconds.
[2019-03-13 15:22:27 +0200][HOST 1][I] Fencing enabled
[2019-03-13 15:22:28 +0200][HOST 1][E] Failed: Unable to obtain correct plug status or plug is not available
[2019-03-13 15:22:28 +0200][HOST 1][E]
[2019-03-13 15:22:28 +0200][HOST 1][E]
[2019-03-13 15:22:28 +0200][HOST 1][E]
[2019-03-13 15:22:28 +0200][HOST 1][E] Fencing error
[2019-03-13 15:22:28 +0200][HOST 1][E] Exiting due to previous error.
```

**Comment by rsmontero** [comment]
Looking at your example:

1. You also have Host affinity to hosts 1 and 6. That will also restrict the suitable hosts. You mention reschedule, OpenNebula will not reschedule a VM to the same host (because it is already running on it, no need to migrate the VM). 
2. UNKNOWN VMs are not automatically rescheduled/recovered. Unknown state needs can be recovered automatically (when the monitor information starts reporting the VM again) or manually (e.g. rebooting). This manual procedure can be tight to the host boot, but this automatically boot of VMs when a hypervisor is rebooted is not currently provided by OpenNebula.

Sorry but I still don't get what new functionality that is expected different from the current logic described in my previous comment.

**Comment by tkald** [comment]
1. that's why I proposed "soft" (checkbox option) affinity / anti affinity rules . If host resources are limited, lets say I have only 2 host and I have 2 vm-s that should run on different hosts but in case of emergency, it's better to run them both somewhere / anywhere (even on the same host) than fail to deploy them.

* Another scenario for "soft" rules - when anti affined service role needs to scale beyond affined host count. Lets say I have 3 hosts to run service. When this anti affined service role scales over 3 instances, 4th vm won't boot on the same reason - no suitable host. So soft rule would log a warning for an example and boot next vm on the next best possible host, even though it's out of suitable hosts.
