### ISSUE TITLE
Sunstone: There is no possibility for hide unwanted or just select type and default storage for uploading images

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1405]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5474, https://dev.opennebula.org/issues/5474
Original Date: 2017-10-19
Original Assignee: Abel Coronado

---

!2.png!

**Comment by rsmontero** [comment]
We still think that makes sense for an end user to select the datastore to upload the image, as it may have different cost, performance, quotas etc... You can always restrict the access to just one datastore

**Comment by kvaps** [comment]
Yes, I know, but there is no way for change the priority for displaying.
For example use case:
*We have 2 datastores in this list:
- first one with our images, and it's not allowed for upload images by simple user
- second one with user images.

There is no way to hide first datastore from this list, or change it to second one by default
any time users should open dropdown menu for select second datastore, because if user will not do this, he will recieve an error.

For now there is only one way for change this behavor: You need to have users datastore with lover id than first one. But this is always difficult, and it is almost never possible to think in advance
