### ISSUE TITLE
Prevent operations to use LOCKED images 

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1412]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5481, https://dev.opennebula.org/issues/5481
Original Date: 2017-10-19

---

If you create new image from the http source, and if it downloads really slowly, it stacks in LOCKED state.

This is really harmful, if you try to connect this image it will stack all your VM, in HOTPLUG state:

```
[Z0][VM][I]: New LCM state is HOTPLUG_PROLOG_POWEROFF
[Z0][TM][E]: missing DISK mandatory attributes (SOURCE, TM_MAD, CLONE, DATASTORE_ID) for VM 5317, DISK 3
[Z0][LCM][E]: prolog_failure_action, VM in a wrong state

```

If you try to create new vm, it will stack in CLONING state, without any logs.

We need to refuse mounting any images in LOCKED state.

**Comment by rsmontero** [comment]
We do not want to let VMs use images in locked state. However, we need to prevent operations using those images (e.g. attach a locked image). Reword the title

**Comment by rsmontero** [comment]
We've looking at this issue. We actually need to let VMs to use images in lock state. For example, when you instantiate to persistent, the images are cloned and the VM waits in CLONING till all the images are usable or in your case downloaded.

However, an attach  disk should not let you use a locked image. This issue is therefore to prevent this situation.
