### ISSUE TITLE
OneGate: Deleting parameters is not possible.

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1414]
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5483, https://dev.opennebula.org/issues/5483
Original Date: 2017-10-19

---

I can not found any possibility for removing parameters.
I can only add a new one or change the current one.

I can run only `onegate vm update -d 'AAA=""'` for free the parameters, but it is not deleting them.

**Comment by kvaps** [comment]
Kubernetes uses minus syntax for removing labels, eg:

```sh
# add label
kubectl label pod <pod_name> aaa=bbb
# remove label
kubectl label pod <pod_name> aaa-
```

We can use same syntax in OneGate Server and OpenNebula API

**Comment by kvaps** [comment]
This problem is still existing

**Comment by al3xhh** [comment]
PRs to merge:

OpenNebula/one: https://github.com/OpenNebula/one/pull/3165 into master and one 5.8
OpenNebula/docs: https://github.com/OpenNebula/docs/pull/560 into master, resolved issues are not updated because I'm waiting for the maintenance for 5.8.2
Tests: https://github.com/OpenNebula/development/pull/578 into master and one 5.8

**Comment by al3xhh** [comment]
PRs to merge in master:

Code: https://github.com/OpenNebula/one/pull/3252
Docs: https://github.com/OpenNebula/docs/pull/597 and https://github.com/OpenNebula/docs/pull/598
