### ISSUE TITLE
Migrate single VM disks  across datastores

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1425]
---

Author Name: **Ruben S. Montero** (@rsmontero)
Original Redmine Issue: 5495, https://dev.opennebula.org/issues/5495
Original Date: 2017-10-24

---

Right now we can migrate a VM across datastores, this issue is to migrate just a single disk and not the whole VM directory.

**Comment by atodorov-storpool** [comment]
The issue is to provide a flexible way to provide "service tiering".
Like we have few datastores with different storage/performance/prices defined as different service tiers by price:
cheap - but slow
medium - acceptable
expensive - fast

a user has a VM with DB disk in the `cheap` tier and want to switch to the `medium` one. There should be a way to (live)"mgrate" the disk to the other datastore.

**Comment by rsmontero** [comment]
Hi @atodorov-storpool 

OK, we were missing context information for this issue. Hopefully the new issue templates will allow us to better track them.

Right now a VM can only run from a single system ds. I think we should reformulate this issue to the ability to run a VM from multiple system DS. Then migration would come for free. However, this is a major development effort that need updates on every component (core, drivers, scheduler...)

**Comment by amenendezASAC** [comment]
Very usefull feature to solve critical situations like a collapsed vCenter LUN because of a big snap that fills it. Migrate a large disk temporarily can solve the problem.

**Comment by paczerny** [comment]
Similar issue #3254

**Comment by tinova** [comment]
duplicated by #6032
