### ISSUE TITLE
Add information about advanced ssh configurations

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1473]
---

Author Name: **OpenNebula Systems Support Team** (OpenNebula Systems Support Team)
Original Redmine Issue: 5543, https://dev.opennebula.org/issues/5543
Original Date: 2017-11-10

---

This may include, use of ssh-agents, reuse of ssh connections..

**Comment by kustodian** [comment]
When I reported this issue to OpenNebula support, I was mostly thinking of making sure that the private SSH key which is used by the `oneadmin` user is only available on the management hosts and not on each node, for better security. So I suggested if it's possible that the management host uses an ssh-agent which forwards the key to the nodes so that they don't have the private key on them, which will result in a much safer OpenNebula cluster.

After reading this issue, it looks like that everything can be done by configuring SSH and nothing needs to be done in OpenNebula.

**Comment by MedicMomcilo** [comment]
Detailed documentation is definitely necessary for this.
We couldn't make oned use ssh-agent even though for oneadmin user it was working properly.

Is there any work-in-progress on how to approach this problem?

**Comment by christian7007** [comment]
This procedure is documented here: http://docs.opennebula.org/5.8/deployment/node_installation/kvm_node_installation.html?highlight=ssh%20agent#step-4-configure-passwordless-ssh

**Comment by MedicMomcilo** [comment]
That was the starting point for us, but details are missing on that note:

> Remember that is neccesary to have running the ssh-agent with the corresponding private key imported before OpenNebula is started. You can start ssh-agent by running eval "$(ssh-agent -s)" and add the private key by running ssh-add /var/lib/one/.ssh/id_rsa.

Does this imply that we should disable opennebula.service, manually login, start tmux/screen session, start agent, and run daemon in foreground?

**Comment by vholer** [comment]
Documentation for SSH was improved. Closing.
