### ISSUE TITLE
Disk, image and datastore attribute precedence

### ISSUE THREAD

**Issue by jmelis** [OpenNebula/one#1512]
# Enhancement Request

## Description

The attribute precedence of disks should be re-evaluated. Currently if an attribute in a datastore is set, it overrides the attributes of those of the disk and of the image.

This logic is defined here:
https://github.com/OpenNebula/one/blob/master/src/image/ImagePool.cc#L447

## Use case

* I define `DRIVER=qcow2` in the datastore, as it will be the default value for all the disks/images.
* I register an image, in that datastore, with a different format, by specifying `DRIVER=raw`.
* The image is always changed to `DRIVER=qcow2` because it has been set in the datastore, but I really want `DRIVER=raw`.

**Comment by hydro-b** [comment]
I would expect that override settings on a disk would go above a globally defined variable.

**Comment by rsmontero** [comment]
It turns out that this fix breaks the marketplace behavior:

1. An marketplace app may define DRIVER=qcow2
2. It is imported in a Ceph datastore
3. When a VM uses that image it is going to be replace by Datastore values an so correctly deployed. This patch breaks this behavior

We are going to revert the changes and move this to 5.6 to try to deal with all use cases

**Comment by atodorov-storpool** [comment]
Not sure is my understandings of the issue correct but in addon-storpool it is resolved updating the _DRIVER_ attribute of the image after import (remotes/datastore/storpool/cp line ~225 )

IMO the order should be Datastore -> Image -> VM disk (in VM template) and exceptions like the marketplace case should be handled by the datastore driver during import when needed

**Comment by vholer** [comment]
Also, we should address this misbehavior:

1. raw image is created with DRIVER=raw
2. in the instantiated VM, the image is "converted" to qcow2 with qcow2 driver
3. if such image is saved, the qcow2 image is created back in the image datastore, but the DRIVER=raw is inherited from the original image (instead of the driver used for the VM disk)

It doesn't make any problems even when the new image is used later, as the driver in VM is again replaced by qcow2. But, it's the inconsistency in the attributes.
