### ISSUE TITLE
KVM CPU feature flags

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/one#1636]
# Enhancement Request
## Description

Be aware of supported CPU flags, and use that information to:
**Automatically display only compatible hosts as live migration target.**   
**Do not try to launch on incompatible hosts.**   

Right now if you try this it'll tell you it's _migrating_, and then return to _running_.
There will be no visible error in the UI, but the VM will simply be on the old host.
Without a message or anything. (so that's a bug of it's own, damn)
Only if you go to the VM log you'll see an error, and same later at the LOG tab where you finally find out it never migrated.
It's wasting time, and much worse, it's **dangerous**. What if someone just tried to "evac" a host to the wrong one? And then shuts it down? yay! :)

## Use case

Make my life easier

First, it's a basic feature.
Second, because I don't wanna memorize all cpu flags supported by all hosts, and not all I disabled in VM templates. That's what computers are for.

## Interface Changes

 
IMM need to report back the flags from /proc/cpuinfo
onevm migrate + sunstone needs to look at cpu flags of all hosts, plus the ones the template turns on/off.
This info is already available, qemu uses it to find out if we're trying an incompatible migration.

# Progress Status
- [x] Branch created 
- [x] Code 
- [x] Testing - QA
- [x] Documentation  (what's new + VM Template reference + review KVM driver )
- [x] Sunstone
  - [x] FSunstone dropdown exposing MONITORING/KVM_CPU_FEATURES
  - [x] RSunstone text area

**Comment by FlorianHeigl** [comment]
wow, thanks for this in-depth feedback 1 year and 3 months after opening the report concerning a functionality that is standard in other solutions much longer than over a decade.

**Comment by tinova** [comment]
Pasting the same as in #1632

The stale bot has been activated in order to detect feedback and contributions that are relevant but have been left behind. Simply a comment (as you see) is enough to not autoclose the ticket, and put it under our radar again. We'd love to have the resource to take all feedback and contributions in, but resources are limited and having hundreds of issues and PRs in the backlog does not help anyone.

**Comment by vholer** [comment]
Extending this FR and summarizing.

**Description**
[Current CPU model selection](http://docs.opennebula.org/5.8/operation/references/template.html#cpu-model-options-section) in the OpenNebula only supports a particular predefined model, host-passthrough or no specification. Since the predefined models doesn't have to contain all hardware security mitigations (e.g., `ssbd` is not enabled by default), if user requests particular CPU features not enabled by default, he has to avoid using `CPU_MODEL` an leverage on libvirt `RAW` specification.

The idea is to extend OpenNebula to
- provide fine-grained VM CPU models on the level of inidividual flags (features), incl. their policies (require, disable, optional, ...)  - https://libvirt.org/formatdomain.html#elementsCPU
- monitor hosts for supported flags
- schedule VMs based on the CPU flags (VM required - host provided)
- disallow live-migrations and reschedule on unsuitable hosts (i.e., respect final set of features enabled in the libvirt domain, not just those specified in the VM template - to make it working for host-passthrough models).

Reference:
- https://qemu.weilnetz.de/doc/qemu-doc.html#cpu_005fmodels
- https://libvirt.org/formatdomain.html#elementsCPU
- support ticket: https://opennebula.zendesk.com/agent/tickets/11889

**Comment by lgrawet** [comment]
Hi,

This is a very important feature as the RAW \<cpu\>\</cpu\> section used to declare custom cpu+flags is overridden by the NUMA settings.

Here is t[he recommended cpu flags list](https://www.qemu.org/docs/master/system/i386/cpu.html), since the predefined models doesn't necessarily contain all hardware security mitigations (as explained by @vholer ). The predefined models features can be found [here](https://github.com/libvirt/libvirt/tree/master/src/cpu_map).

This setting should be accessible globally like [this is the case in OpenStack](https://docs.openstack.org/nova/latest/admin/cpu-models.html) as well as per cluster, host and vm template basis.

Many thanks !

**Comment by tinova** [comment]
need Fsunstone test
