### ISSUE TITLE
Host listing - Real used cpu should use real total cpu as base 

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#1756]
# Enhancement Request
## Description

In hosts listing I enable Real CPU column to see real usage. This column uses total cpu value including overcommitment as base and calculates percentage value of use from overcommitment value.

I think, that it should be calculated from real total cpu. Metrics is also in host detail and dashboard.

Real memory is calculated same way, so it should be changed too.

## Use case

Better management and view of compute nodes.

## Interface Changes

 
![](https://s13.postimg.org/54a6qe27b/Screen_Shot_2018-02-19_at_10.06.08.png)
![](https://s13.postimg.org/enjvk4knb/Screen_Shot_2018-02-19_at_09.51.56.png)
![](https://s13.postimg.org/77klyg79j/Screen_Shot_2018-02-19_at_10.02.50.png)

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Hello @feldsam 

This monitoring information has suffer a complete redesign with the new monitoring system. Currently the information provided by the call `one.hostpool.info` doesn't contain the **monitoring** information, this is to reduce the size of the messages.

So currently this is not possible to show that information in the list and that's why it shows the information with the over commitment.

So, as workaround you can use the `onehost show` command, you have there all the information related with the monitoring separated from the over commitment:

```
MEMORY                                                                          
  TOTAL               : 15.3G               
  TOTAL +/- RESERVED  : 15.3G               
  USED (REAL)         : 7G                  
  USED (ALLOCATED)    : 1024K               
CPU                                                                             
  TOTAL               : 800                 
  TOTAL +/- RESERVED  : 1800                
  USED (REAL)         : 152                 
  USED (ALLOCATED)    : 100 
```
As you can see, you can check the **total** and also the **total + over commit** value.

In Sunstone it's true that the information is not showed correctly in the details tab, that will be fixed for the next release.
