### ISSUE TITLE
Attach a new volatile disk

### ISSUE THREAD

**Issue by ghost** [OpenNebula/one#1799]
# Bug Report
## Version of OpenNebula
- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [X] 5.4.7
- [ ] Development build

## Component
- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [X] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
The workflow to add a volatile disk to an existing VM is suboptimal. If you have more then one datastore you can't choose the favor one.

### Expected Behavior
Going into the VM -> Storage -> Attache Disk -> volatile disk and now you should have the option to choose the datastore.

### Actual Behavior
At the moment you have to create a new datastore image as datablock and then you have to add this image to the vm and adjust the capacity of the disk.

**Comment by atodorov-storpool** [comment]
IMO it is a feature because by definition the volatile images are located in the SYSTEM datastore and currently the VM have only one SYSTEM datastore so for me it is not a bug.

Most probably you mean a feature to have a shortcut/or simpler interface?/ to create and attach an empty image from selected IMAGE datastore and delete it in the when a VM is terminated(mimicking the current volatile behavior)?

**Comment by rsmontero** [comment]
Yes, @atodorov-storpool is right the datastore is implicitly defined, as the disk will be created in the system datastore. Closing.
