### ISSUE TITLE
Own ssh-agent for key forwarding

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#2152]
# Enhancement Request
## Description
have our own ssh-agent running with fixed socket path for forwarding the private key from the frontend to the hypervisor nodes

## Interface Changes

 

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by MedicMomcilo** [comment]
We were looking at the documentation for ssh-agent, but it is not very detailed.
So, we tried configuring start-up script and setting environment for ONE systemd service.
However, all attempts failed.

When we manually configured and ran ssh with the agent, we can successfully traverse hosts.
Thus, configuration should be OK, it is just that oned is running in completely separate session.

Is this at all possible currently?
What is the proper method of setting this?

**Comment by alloran** [comment]
I solved this by running ssh-agent as systemd service and adding ssh-agent socket path to /etc/one/defaultrc


```
$ cat /etc/systemd/system/opennebula-ssh-agent.service
[Unit]
Description=SSH key agent
After=opennebula.service

[Service]
Type=simple
User=oneadmin
Group=oneadmin
Environment=SSH_AUTH_SOCK=/run/one/ssh-agent.sock
ExecStart=/usr/bin/ssh-agent -D -a $SSH_AUTH_SOCK

[Install]
WantedBy=default.target
```
```
$ cat /var/lib/one/.ssh/config 
Host *
  StrictHostKeyChecking=accept-new
  ForwardAgent yes
  AddKeysToAgent yes
```
```
$ cat /etc/one/defaultrc
...
SSH_AUTH_SOCK="/run/one/ssh-agent.sock"
```

**Comment by vholer** [comment]
Anton from StorPool has an addon for ssh-agent support:
https://forum.opennebula.org/t/introducing-addon-sshagent-a-ssh-agent-service-configuration-for-opennebula/7952

Hello @atodorov-storpool , would you be willing to open PR with necessary changes (so that you preserve the credits for the work), it doesn't have to be a final state, just some state we'll finish. Otherwise, we can be take the addon and manage the merging?

**Comment by atodorov-storpool** [comment]
I think it is honest to attribute both of us by merging the best from both implementations as @alloran version has its benefits too. I'll try to help outlining the pros in each implementation:

* (alloran) SSH_AUTH_SOCK created in /run/one/ssh-agent.sock - being on _tmpfs_ eliminate the need of `ExecStartPre` introduced in addon-sshagent
* (atodorov) The SSH_AUTH_SOCK is provided to all _oneadmin_ sessions via systemd _Environment_ and a shell export via`.bashrc` - The @alloran idea is to provide the service primary to the MADs via _/etc/one/defaultrc_. This will cause trouble to files/services not aware of this file at one side, also, for me at least, it is easier to debug things just changing the user with `su - oneadmin`, otherwise I need to `source /etc/one-defaultrc` first to have the socket in the environment before trying to connect to a service...
* (atodorov) The @alloran idea is to define the service as a standalone one. I think that using the systemd's directives it is better to follow the _opennebula_ service so there is no need to take care 'kick'-ing additional service when something is not going right.
* (on par?) IMO The Service Type definition(simple vs forking) has same result as systemd handle both cases.

**Comment by atodorov-storpool** [comment]
> (alloran) SSH_AUTH_SOCK created in /run/one/ssh-agent.sock - being on tmpfs eliminate the need of ExecStartPre introduced in addon-sshagent

Re-thinking, I think that ExecStartPre should be kept as a second safeguard for the cases when the opennebula service is restarted. It was tested and proven to "resolve" a lot of fail scenarios that do not include host reboot.

:)

**Comment by vholer** [comment]
Thanks for the comments, @atodorov-storpool. I'm thinking about the points

- `SSH_AUTH_SOCK` is definitely nice to have in `/run`

- Agent service should also
  - restart on failure
  - automatically add the default key (so that `AddKeysToAgent yes` is not necessary)
  - have it triggered same way as e.g. scheduler (just `opennebula.service:Wants=opennebula-ssh-agent.service`); this keeps it mandatory by default, but service can be masked to disable

- Default access to agent
  - keep it available only for OpenNebula service (not for whole session) is the safe option
  - set access via service environment variable, `defaultrc` not necessary
  - NICE TO HAVE: `...-ssh-agent.service` might generate env. file with socket and `opennebula.service` reads the `EnvironmentFile=-/run/one/ssh-agent.env` (instead of always set socket path). This should allow to mask / disable ssh-agent service, without affecting the OpenNebula service env. and makes it completely optional and independent. 

- TBD: Similarly as with env. file above, it would be nice to allow agent forwarding automatically if agent service is running without need to have it enabled in the `ssh.config`. As it's the only thing necessary to configure. I don't know how to easily achive that, as e.g. I can't see way how to enable SSH agent forwarding via env. variable.

**Comment by alloran** [comment]
Maybe just redefine $SSH and $SCP variables defined in `/var/lib/one/remotes/scripts_common.sh` ?

`SSH="ssh -o ForwardAgent=yes"`

**Comment by atodorov-storpool** [comment]
Hi @vholer, @alloran, 

Following your thoughts here are my comments/notes:
> restart on failure

Definitely.
> automatically add the default key (so that AddKeysToAgent yes is not necessary)

Well, it is questionable what is the "default" key. `AddKeysToAgent yes` delegate this responsibility to the ssh client. Currently, the ssh client has `~/.ssh/id_dsa`, `~/.ssh/id_ecdsa`, `~/.ssh/id_ed25519` and `~/.ssh/id_rsa` for protocol version 2 (via man 1 ssh _identity_file_) and if there is a change in the future the ssh client will take care to handle the new "defaults". That is the only reason to have to have AddKeysToAgent enabled by default.

> have it triggered same way as e.g. scheduler (just opennebula.service:Wants=opennebula-ssh-agent.service); this keeps it mandatory by default, but service can be masked to disable

I just need to check but I think that in this case the opennebula-ssh-agent.service will continue working after the opennebula.service is stopped?
> keep it available only for OpenNebula service (not for whole session) is the safe option
> set access via service environment variable, defaultrc not necessary

Agree
> NICE TO HAVE: ...-ssh-agent.service might generate env. file with socket and opennebula.service reads the EnvironmentFile=-/run/one/ssh-agent.env (instead of always set socket path). This should allow to mask / disable ssh-agent service, without affecting the OpenNebula service env. and makes it completely optional and independent

If I am not wrong this will generate random path to the socket, which will resolve the need of deleting the socket (get rid of "socket already in use" error). But then if the opennebula-ssh-agent.service crashes and being restarted this will create a new socket and the complexity to  reload the opennebula.service environment will rise.

> TBD: Similarly as with env. file above, it would be nice to allow agent forwarding automatically if agent service is running without need to have it enabled in the ssh.config. As it's the only thing necessary to configure. I don't know how to easily achive that, as e.g. I can't see way how to enable SSH agent forwarding via env. variable

On this topic, I think that we are on the same page with @alloran :). I think it could be even more tighten. The agent forwarding is needed only for VM Migrate, Undeploy and disk Clone. So I think the best solution is to have the agent forwarding enabled only for the needed actions in the MAD scripts. Something like `ssh -A host ...` in dedicated functions like `ssh_exec_agent`, or something like that... Well this will extend the work on the patch to merge so this could be improved on a later iteration?

**Comment by vholer** [comment]
Hello guys,

> > automatically add the default key (so that AddKeysToAgent yes is not necessary)
> 
> Well, it is questionable what is the "default" key. `AddKeysToAgent yes` delegate this responsibility to the ssh client. Currently, the ssh client has `~/.ssh/id_dsa`, `~/.ssh/id_ecdsa`, `~/.ssh/id_ed25519` and `~/.ssh/id_rsa` for protocol version 2 (via man 1 ssh _identity_file_) and if there is a change in the future the ssh client will take care to handle the new "defaults". That is the only reason to have to have AddKeysToAgent enabled by default.

for sure, user can configure `AddKeysToAgent` if he wants / needs. The motivation is only to make it usable without any extra configuration from the start for the basic deployment, when oneadmin's keys are generated by post install scripts.

Without any parameters, `ssh-add` adds all the default keys:

```
$ man ssh-add
...
DESCRIPTION
     ssh-add adds private key identities to the authentication agent,
     ssh-agent(1).  When run without arguments, it adds the files
     ~/.ssh/id_rsa, ~/.ssh/id_dsa, ~/.ssh/id_ecdsa, and ~/.ssh/id_ed25519.
```

That should be enough.

> > have it triggered same way as e.g. scheduler (just opennebula.service:Wants=opennebula-ssh-agent.service); this keeps it mandatory by default, but service can be masked to disable
> 
> I just need to check but I think that in this case the opennebula-ssh-agent.service will continue working after the opennebula.service is stopped?

Yes, it stays independent and survives the OpenNebula service restart.

> > NICE TO HAVE: ...-ssh-agent.service might generate env. file with socket and opennebula.service reads the EnvironmentFile=-/run/one/ssh-agent.env (instead of always set socket path). This should allow to mask / disable ssh-agent service, without affecting the OpenNebula service env. and makes it completely optional and independent
> 
> If I am not wrong this will generate random path to the socket, which will resolve the need of deleting the socket (get rid of "socket already in use" error). But then if the opennebula-ssh-agent.service crashes and being restarted this will create a new socket and the complexity to reload the opennebula.service environment will rise.

I meant more preserve the fixed socket name as it was proposed here, but to affect the OpenNebula as least as possible -- propagate the SSH_AUTH_SOCK only if the agent successfully started. Silly (non-working) example to describe the approach:

opennebula-ssh-agent.service:
```
ExecStartPre=-/bin/rm -f /run/one/ssh-agent.env $SSH_AUTH_SOCK
ExecStart=ssh-agent ....
ExecStartPost=/bin/sh -c "echo SSH_AUTH_SOCK='$SSH_AUTH_SOCK' >/run/one/ssh-agent.env"
ExecStopPost=-/bin/rm -f /run/one/ssh-agent.env $SSH_AUTH_SOCK
```

opennebula.service:

```
EnvironmentFile=-/run/one/ssh-agent.env
```

Yeah, cleanups are there, but systemd will take care of them (before / after). But, mainly if there is no SSH agent service running, it won't export empty SSH_AUTH_SOCK in OpenNebula service. But, maybe it's not worth??

> On this topic, I think that we are on the same page with @alloran :). I think it could be even more tighten. The agent forwarding is needed only for VM Migrate, Undeploy and disk Clone. So I think the best solution is to have the agent forwarding enabled only for the needed actions in the MAD scripts. Something like `ssh -A host ...` in dedicated functions like `ssh_exec_agent`, or something like that... Well this will extend the work on the patch to merge so this could be improved on a later iteration?

Nice!! Yes, we'll better need a dedicated function with a generic naming, as it might also do a Kerberos credentials delegations (`ssh -K`) for the deployments not relying on SSH keys.

Thanks to all for the comments,
Vlastimil

**Comment by ospalax** [comment]
Done, OpenNebula 5.12 comes with a new service `opennebula-ssh-agent` which solves this issue.

**Comment by albert0marti** [comment]
Thank you to all the people that contributed to this!! :mechanical_arm:
