### ISSUE TITLE
Upgrade to NoVNC 1.0

### ISSUE THREAD

**Issue by hoerup** [OpenNebula/one#2346]
Sunstone currently uses novnc 0.5.1 which is over 3 years old

Plase consider upgrade to novnc 1.0 which has lots of fixes and improvements - including better keyboard support.

https://github.com/novnc/noVNC/releases

**Comment by tinova** [comment]
check also if we can upgrade to python3

**Comment by vholer** [comment]
Python 3 was covered here:
https://github.com/OpenNebula/one/issues/1012

**Comment by vholer** [comment]
Since we are touching the VNC code, it would be great if some small feature could be considered:
- support scaling - add a control to enable scale of the VNC box (there should be 3 modes supported ~ none, local, remote)

(Man) Use case 1 - If I have a browser window 1600x1200, it shouldn't be fixed to the resolution set in the virtual machine e.g. 800x600, but be able to communicate the custom size and adjust on both sides --> as I result, the VNC content will try to fit as much as possible into 1600x1200, and the virtual machine desktop resolution will follow these dimentions. I.e., VM desktop will have a custom size of nearly 1600x1200. Browser VNC pixels will be always 1:1 to what is on VM desktop (no stretching, just desktop resize).

Use case 2 - Having a small VM desktop resolution leads to small VNC box. It would be great, if the VNC content can be just stretched to the size of window resulting just in a bigger image. Desktop size in the VM won't change, just the VNC image will be stretched.

**Comment by tinova** [comment]
Needs testing

**Comment by tinova** [comment]
continuing in #3434
