### ISSUE TITLE
Ceph premigrate called in migrate_other breaks shared system datastores 

### ISSUE THREAD

**Issue by infernix** [OpenNebula/one#2351]
**Description**
Migrating a VM with 1 disk from a shared datastore X (which uses an NFS mount under `/var/lib/one/datastores/X` between all hosts for metadata) and an additional disk from a ceph datastore Y **and with its system datastore (which is also NFS mounted between all hosts for metadata) set to Z** fails live migration because the ceph premigrate code removes `/var/lib/one/datastores/X/$VMID` when called by `migrate_other`.

This happens seemingly because this VMs system datastore is set to one that uses NFS to share (meta)data between hypervisors, and `migrate_other` calls ceph `premigrate` which is hardcoded for ssh type system datastores.

**To Reproduce**
1. Create a VM with a disk in a shared datastore, and make sure its system datastore is also shared (NFS)
2. Add an additional ceph disk to this VM
3. Live migrate the VM between hypervisors
4. See it fail because of ceph removing the VM_PATH in the (nfs shared) system datastore

**Expected behavior**
Ceph should not assume that a VMs system datastore is of type ssh

**Details**
 - Affected Component: Storage TM_MAD premigrate: https://github.com/OpenNebula/one/blob/6f85151d8705b22cea6695102c9bfd83dc7f00a9/src/tm_mad/ceph/premigrate#L70
 - Hypervisor: KVM
 - Version: 5.2 but probably up to current master

**Additional context**
I'm not sure what the right approach is here since we wouldn't want to put knowledge of other datasource drivers into the ceph code, but what it currently does is too blunt.

Perhaps ceph pre/post/failmigrate scripts should check DSID and do nothing if DSID is not a ceph datastore?

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by infernix** [comment]
@atodorov-storpool I think you would see this problem with Storpool as well (with a VM that has storpool as system datastore with DS_SHARED=yes and has an additional ceph disk).

**Comment by atodorov-storpool** [comment]
Hi @infernix ,

For the case when _tm/ceph/premigrate_ is called by other SYSTEM _tm_mad_ via _migrate_other()_, there is an additional argument passed (that contain the root TM_MAD) and it will  be detected in the _tm/ceph/premigrate_ script and it should bail out:
https://github.com/OpenNebula/one/blob/6f85151d8705b22cea6695102c9bfd83dc7f00a9/src/tm_mad/ceph/premigrate#L56

When the _TM_MAD=ceph_ and the SYSTEM datastore is on NFS shared filesystem the _migrate_other()_ is skipping tm/ceph/premigrate:
https://github.com/OpenNebula/one/blob/6f85151d8705b22cea6695102c9bfd83dc7f00a9/src/tm_mad/tm_common.sh#L148
But then the primary _tm/ceph/premigrate__ will delete the "remote" **before** _migrate_other()_ is called... This issue should be resolved it the ceph's premigrate/postmigrate script IMO.

In _addon-storpool_ it is handled by a separate datastore argument that is handled by the driver and actions are taken accordingly.

Could you clarify what is the SYSTEM and IMAGE datastore setup, and what is mounted over NFS in your case?

**Comment by infernix** [comment]
OK, so we have several datastores:
- 0 being the default ONE system datastore, mounted over nfs
- 100 being a CEPH SYSTEM datastore. It doesn't need to be shared over NFS in /var/lib/one/datastores/
- 101 being a CEPH IMAGE datastore
- 102 being a ScaleIO SYSTEM datastore, which is shared over NFS for metadata (much like Storpool with DS_SHARED=YES)
- 103 being a ScaleIO IMAGE datastore

The VM in question has:
- `SCHED_DS_REQUIREMENTS = "NAME=scaleio_system"` - so its system datastore is on ScaleIO
- Disk 1 being the context ISO, which lives in the ScaleIO SYSTEM datastore
- Disk 3 being a ScaleIO IMAGE (non-persistent)
- Disk 4 being a CEPH IMAGE (persistent)

VMs metadata gets stored in /var/lib/one/datastores/102/84 which is the ScaleIO SYSTEM datastore, shared over NFS.

So, in this case, `tm/ceph/premigrate` is being called by the ScaleIO SYSTEM `tm_mad`. But it does not pass any additional argument in `$7`. It get's called like this:

`/var/lib/one/remotes/tm/scaleio/premigrate hv1 hv2 /var/lib/one/datastores/102/84 84 102 <base64_encoded_xml>`

So the script happily does an `rm -rf` on it and live migration fails.

And I can't figure out where it is supposed to add a 7th argument either. I see you added` it to ceph scripts in 019683206560ab0eae06f93c343269580f5779b8 but where are `premigrate` arguments getting set?

**Comment by atodorov-storpool** [comment]
Here is how it works.

OpenNebula is calling the _tm/SYSTEM_TM_MAD/premigrate_ with 6 arguments. At the end of the script _migrate_other()_ is called with all arguments passed to it. The migrate_other function parsing the received TEMPLATE (the 6th argument) for all disk TM_MADs and for each TM_MAD that differ from the SYSTEM_TM_MAD _premigrate_ is called with all native arguments plus a 7th argument that contains the SYSTEM_TM_MAD. This way the _/tm/OTHER_TM_MAD/premigrate_ knows that is called in "slave" context and should behave accordingly.

So for example when there is a ceph disk attached and the SYSTEM_TM_MAD is `shared`, migrate_other() from the end of _tm/shared/premigrate_ is calling _/tm/ceph/premigrate_  with a 7th argument that contain 'shared'. This way the ceph's premigrate knows that it is called not as a SYSTEM_TM_MAD and does nothing. 

In contrast when _/tm/storpool/premigrate_ is called in the "slave" context (with a 7-th argument) it is activating the StorPool backed disks on the destination host.

I couldn't find the "scaleio" driver in [OpenNebula's addon catalog](https://opennebula.org/addons/catalog/) nor with a quick google search for _scaleio opennebula addon driver_ so I do not know how it works. 

That said,
>  102 being a ScaleIO SYSTEM datastore, which is shared over NFS for metadata (much like Storpool with DS_SHARED=YES)

I believe that you should not compare addon-storpool with other drivers because besides the extended features it provides, it is following its own logic to decide what is the underlying filesystem. For example, as I've already wrote the _DS_SHARED_ is always _yes_ for both shared and non-shared filesystem under the SYSTEM datastore ;)

**Comment by xorel** [comment]
I am afraid that in version 5.2 your setup (CEPH + shared FS) is not working correctly.  This _should_ be fixed in 5.4. However since 5.6 it is no longer recommended setup. In 5.6 you should use either Ceph mode or SSH mode (http://docs.opennebula.org/5.6/deployment/open_cloud_storage_setup/ceph_ds.html#datastore-layout)
