### ISSUE TITLE
random: wait-for-root: uninitialized urandom read (16 bytes read)

### ISSUE THREAD

**Issue by nordurljosahvida** [OpenNebula/one#2487]
**Description**

After having performed an APT-upgrade [I kept the existing version of GRUB when prompted] all of my VMs won't start anymore, halting instead their boot on:

`random: wait-for-root: uninitialized urandom read (16 bytes read)`

<img width="752" alt="screen shot 2018-10-08 at 17 39 09" src="https://user-images.githubusercontent.com/1408210/46619395-4b73b180-cb22-11e8-91db-f722d30b5df5.png">

They're all Ubuntu 18 KVM [downloaded from the marketplace] running on an Ubuntu 16 host machine and one v 5.4.13.

**To Reproduce**

Do what I did above.

**Expected behavior**

They should boot.

**Details**

 - Affected Component: core
 - Hypervisor: KVM
 - Version: 5.4.13

**Additional context**

None that I can think of.

Thanks in advance for your help.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FoZo** [comment]
I have same problem.
I tested it with Centos and Ubuntu 18.04 as kvm hypervisors.

**Comment by frootmig** [comment]
Same problem here. All Ubuntu VMs refuse to boot due to this.

**Comment by vholer** [comment]
Download latest Ubuntu images from the Marketplace, they are already fixed.

Problem is a caused by Grub configuration overrides in `/etc/default/grub.d`, which brings back the configuration for the serial console on Grub refresh (mostly caused by kernel upgrade) and next reboot. As a workaround, delete directory `/etc/default/grub.d` from all your running Ubuntu instances and trigger `update-grub`.

To fix a VM which doesn't boot, you have to power-off the VM and add serial console device via raw parameters for the libvirt. Steps:

- power off VM
- click on "Conf" -> "Update Configuration"
- click on "Other"
- place into "Data" box:

```
<devices><serial type='pty'><target port='0'/></serial><console type='pty'><target type='serial' port='0'/></console></devices>
```

- power on VM

**Comment by frootmig** [comment]
@vholer Just for clarification: you mean placing the XML snipped in
* "Conf" -> "Update Configuration"
* Click "Tags"
* Under "RAW data" with type "kvm" in the data Box

Another option is using the advanved tab and add to the template
`RAW = [
  DATA = "<devices><serial type='pty'><target port='0'/></serial><console type='pty'><target type='serial' port='0'/></console></devices>",
  TYPE = "kvm" ]`

**Comment by vholer** [comment]
> It is a bit confusing, that the marketplace apps do not show an updated date. And I'm still not sure if it's possible to update the image used for the existing VMs or if I should recreate them.

True, we provide a register time (creation time), but it doesn't change since the very first release. Next time maybe we can abuse this attribute to provide date the appliance was refreshed. Thank you for the feedback.

> To get the VMs with the old template up and running again just for clarification: you mean placing the XML snipped in ...

Yeah, it differs a little for ONE 5.4 and ONE 5.6, your steps are correct for 5.6. Or, edit the template in advanced mode. Both are OK.

**Comment by frootmig** [comment]
Thanks for your help!
