### ISSUE TITLE
OneFlow VM metadata expansion & inheritance

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/one#2585]
**Description**
Be able to define VM context extensions on a global level, not just per role.

**Use case**
Use the same templates, but drive them completely from a per-service level
(i.e. a major software version to use in all roles)

**Interface Changes**
would like to enter it in service template of sunstone
also when instantiating, maybe similar to how you can adhoc nets (i only partially grasp their usecase though)

**Additional Context**
By all means, I'd also want to really have inheritance, so be able to overwrite an existing role setting (or flag it readonly), and TOTALLY I'd want to also inject into a VMs template content (raw fields, or custom vars, lots of options here, and all could be used well).
I think the main part though is to have consistency.
at least, role parameters should be able to pull defaults from the service.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
We have a campaign open for OneFlow for the next release, and this is a long overdue feature. Definitely will address in 5.12.

**Comment by tinova** [comment]
Hi Florian,

Finally we got to review this. There has been some improvements and bug fixes in 5.12 and 6.0 relevant to this issue.

In particular this one I think it addresses this at least partially: https://github.com/OpenNebula/one/issues/5152. This should let you define user inputs at the service level that will then be applied to the CONTEXT section of the templates. 

Not sure if this covers your use case, could you please give us an example otherwise? I'll move this for 6.2 as unfortunately i don't think we can realistically tackle any more features for 6.0.

**Comment by FlorianHeigl** [comment]
@tinova it's been so long that I have a hard time recalling any of this.

My usual use cases are "a new version of a software was released, i want to run 20 vms with 20 OS names/versions and  test it installs flawlessly there".

I think the referenced issue describes functionality that could be used for this.
I'm not 100% sure, I think today I would revive the corpse of `addon-metadata` which can probably give me more.

I'm gonna close this one since the other one likely covers it.
