### ISSUE TITLE
XML inconsistency in the output of 'onevm list -x '

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#2997]
**Description**
After upgrade to one-5.8.0 the xml output of `onevm list -x` has different(non-indented) view for non-runnng VMs.

**To Reproduce**
1. Define one5.6.2 with VMs in different states - some running, some powered off, some undeployed, etc.
2. Upgrade to one-5.8.0
3. Issue `onevm list -x`

**Expected behavior**
The output of onevm list should be consistent (and indented?)

**Details**
 - Affected Component: [Core]
 - Hypervisor: [KVM]
 - Version: [5.8.0]

**Additional context**
Probably related to #2995
After power cycling a VM the output is OK.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
This is related with #2489. Now "one.vmpool.info" call returns a reduce version of the body field in order to improve the performance for large deployments. This new field is generated by the DB migrator without indentation. As son as the core overwrite it it will be show indented. 

If you need to see an indented output you can use "xmllint --format" command or if you are just interested in one VM use "one.vm.info" call which returns the complete body of the VM.

**Comment by christian7007** [comment]
You still can do that, the reduce version of the pool include the last history record and the DS_ID field:

`<HISTORY_RECORDS>
    <HISTORY>
      <OID>1</OID>
      <SEQ>1</SEQ>
      <HOSTNAME><![CDATA[localhost]]></HOSTNAME>
      <HID>0</HID>
      <CID>0</CID>
      <DS_ID>0</DS_ID>
      <ACTION><![CDATA[11]]></ACTION>
    </HISTORY>
  </HISTORY_RECORDS>`

**Comment by atodorov-storpool** [comment]
Yep, there will be an transient issue immediately after the upgrade but I'll address it in the script.

Thanks for the clarification
