### ISSUE TITLE
Live migration fails with volatile disk attached on LVM datastore

### ISSUE THREAD

**Issue by xorel** [OpenNebula/one#3203]
**Description**
Live migration fails with volatile disk attach for LVM datastore

**To Reproduce**
Setup LVM datastore, attach a volatile disk to the VM, try live migration.

**Expected behavior**
migration success

**Details**
 - Affected Component: LVM datastore drivers
 - Hypervisor: KVM
 - Version: 5.8

**Additional context**
https://forum.opennebula.org/t/bug-with-migration-vms-that-using-volatile-disks-on-lvm/7112

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment]
IMHO this solution is only partial, forcing third-party addons to do patches in place like 
[addon-storpool](https://github.com/OpenNebula/addon-storpool/blob/master/patches/vmm/5.8.0/attach_disk.patch) and [one-addon-3par](https://gitlab.feldhost.cz/feldhost-public/one-addon-3par/blob/master/vmm/kvm/attach_disk) maintained by @feldsam 
Also, it solves only disk hotplug, but libvirt in the recent CentOS versions rejects VM deploy because the volatile disk is with configuration as "file" not on shared filesystem ...

Why not just allow to have a SYSTEM datastore with TYPE=BLOCK?

**Comment by feldsam** [comment]
I agree with @atodorov-storpool , why system ds have to be just type file?
