### ISSUE TITLE
Can't scale service role - can't dup NilClass

### ISSUE THREAD

**Issue by tkald** [OpenNebula/one#3265]
**Description**
Since One 5.8 I'm getting error if I try to scale service role either from Sunstone or command line.
Error html output attached as txt
[error.txt](https://github.com/OpenNebula/one/files/3109403/error.txt)
Automatic scaling seems to work though.

**Expected behavior**
Service scales as expected

**Details**
 - Affected Component: [oneflow]
 - Hypervisor: [KVM]
 - Version: [5.8.0 and 5.8.1]

**Additional context**
Ubuntu 16.04.6 LTS

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
Hello @tkald 

I have done many tests with the following template:

```
{
  "DOCUMENT": {
    "ID": "0",
    "UID": "0",
    "GID": "0",
    "UNAME": "oneadmin",
    "GNAME": "oneadmin",
    "NAME": "test",
    "TYPE": "101",
    "PERMISSIONS": {
      "OWNER_U": "1",
      "OWNER_M": "1",
      "OWNER_A": "0",
      "GROUP_U": "0",
      "GROUP_M": "0",
      "GROUP_A": "0",
      "OTHER_U": "0",
      "OTHER_M": "0",
      "OTHER_A": "0"
    },
    "TEMPLATE": {
      "BODY": {
        "name": "test",
        "deployment": "straight",
        "description": "",
        "roles": [
          {
            "name": "RoleA",
            "cardinality": 1,
            "vm_template": 0,
            "elasticity_policies": [

            ],
            "scheduled_policies": [

            ]
          }
        ],
        "shutdown_action": "terminate-hard",
        "ready_status_gate": false
      }
    }
  }
}
```

I have scaled up and down and I don't get any error. We have made a huge [revamp](https://github.com/OpenNebula/one/issues/4132) of the OneFlow component, so maybe this bug is already solved.

Could you please try it in the current [5.12](https://opennebula.io/firework/) release and check if it still fails for you. If it still fails, it would be very helpful if you can send me your database, so I can try to reproduce with it.

Best,
Álex.

**Comment by al3xhh** [comment]
Closing as we can not reproduce it, if further information is provided we will reopen it.
