### ISSUE TITLE
Installing opennebula-node-lxd wipes out existing snap lxd images

### ISSUE THREAD

**Issue by shemgp** [OpenNebula/one#3349]
**Description**
Installing opennebula-node-lxd on a servicer with existing snap based lxd installation installs apt based lxd and wipes out lxd snap installation.  Now my containers are gone.

**To Reproduce**
sudo apt-get install opennebula-node-lxd

**Expected behavior**
It would be great if you don't depend on apt lxd, but instead be able to use snap based lxd.

**Details**
 - Affected Component: Drivers
 - Hypervisor: LXD
 - Version: 5.8.1-1

**Additional context**
This is on Ubuntu 18.04.2 LTS version.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
I hope you didn't lose anything, just your default LXD switched from snap to native installation. Now you have both installed, but native installation is new default preferred one. All your images from snap based installation should be still there, snap should use different paths. You can try to control the snap based installation directly over /snap/bin/lxc commands, or revert back by uninstlaling the lxd (and dependent) package(s).

Since OpenNebula 5.8.2,we support both installation types with help of the metapackage opennebula-lxd-snap  on Ubuntu 16.04 and 18.04. But, the LXD package is still the default installation way even though the snap is already installed. User must handle the installation carefully:

http://docs.opennebula.org/5.8/deployment/node_installation/lxd_node_installation.html#installing-on-ubuntu

Please note 5.8.2 is a maintenance release.

**Comment by vholer** [comment]
Related https://github.com/OpenNebula/packages/issues/65
