### ISSUE TITLE
Service stuck in SCALING state

### ISSUE THREAD

**Issue by meier-rene** [OpenNebula/one#3433]
**Description**
If I scale a service some new VM gets deployed. If there are not enough resources to deploy the new VMs the service will stay in the SCALING state. I can not find any way to get the service back to normal RUNNING state.

**To Reproduce**
Have any service running. Scale a role to a size which does not fit into your cluster. See some VMs in PENDING state. If I delete the PENDING VMs they get redeployed. If I try to scale down the service to a size which fits the cluster, I get an error message in sunstone and no message from oneflow. Only solution is to delete the service which also kills all other running VMs of this service.

**Expected behavior**
There needs to be a way to get the service back to normal state.

**Details**
 - Affected Component: Sunstone, Scheduler
 - Hypervisor: KVM
 - Version: 5.8.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
With the new OneFlow, this works as following:

- You scale the service, it goes to **SCALING**.
- Then you remove the virtual machine as it can't scale.
- The OneFlow noticed that delete operation and puts the service in **COOLDOWN**.
- Then the watchdog updates the cardinality to the previous one, as it couldn't scale.

So I think the bug is solved in the new version. Closing it, if the situation repeats in the future we will reopen it.
