### ISSUE TITLE
vCPU not working for LXD VMs

### ISSUE THREAD

**Issue by shinebayar-g** [OpenNebula/one#4069]
**Description**
LXD VM's vCPU is not working as expected. I've checked via `htop` on host machine and lxd guest VM.

![image](https://user-images.githubusercontent.com/3091558/71555181-ff34ca00-2a63-11ea-82a6-e7a26848b043.png)

**To Reproduce**
I've created LXD VM with this settings.

![image](https://user-images.githubusercontent.com/3091558/71555186-1ffd1f80-2a64-11ea-80bc-98eba485bfe6.png)

**Expected behavior**
I assume LXD VM will see 2 cores available to use, but actually those 2 cores will be equivalent of 0.4 core of host machine?

**Details**
 - Affected Component: Compute
 - Hypervisor: LXD 
 - Version: 5.10.1

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dann1** [comment]
The LXD CPU limitation is explained a bit [here](https://lxd.readthedocs.io/en/latest/instances/#cpu-limits). Your container should have a config key `limits.cpu.allowance: 40%`. This behaves like:

> When using a percentage value, the limit will only be applied when under load and will be used to calculate the scheduler priority for the instance, relative to any other instance which is using the same CPU


Currently the LXD driver soft limits the CPU. Maybe we can add a key to the LXD VM template to force a hard limit, which will apply a time constraint for the CPU, instead of a `%` value, or just use a hard limit (with it's downside)

If you are interested in this, open a feature request and if enough interest is reached, it could be worked on. Also a PR is always welcome.

**Comment by shinebayar-g** [comment]
Then why vCPU option is enabled in first place? Appropriate option would be better solution for this issue to be "Closed"

**Comment by dann1** [comment]
vCPU only stands for the amount of cores inside the container, which is 100% OK. according to your top. The other parameter `CPU` is the one I was discussing. Read the documentation.
