### ISSUE TITLE
sunstone save as template dialog does not honour instantiate_persistent setting

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#4093]
**Description**

tabs/vms-tab/dialogs/saveas-template/html.hbs does not have any hiding the persistence option based on the setting of features.instantiate_persistent in the view config. If this value is false the checkbox should be hidden

**Details**
 - Affected Component: Sunstone
 - Version: 5.10.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
The `Make the new images persistent` checkbox at Save as Template dialog can be used even if the VM is not instantiated as persistent because both are different ways to obtain the same result.

- `Make the new images persistent` generates a new VM Template with a copy of all the images located at the current VM, this can be done at any moment while your VM has the state POWEROFF.

- `Instantiate as persistent` option creates a new VM with is persistent, but this is done when the user is creating a VM.

In this case the `features.instantiate_persistent` in the view config is about the `Instantiate as persistent` option and this checkbox at `tabs/vms-tab/dialogs/saveas-template/html.hbs` makes reference to `Make the new images persistent` option.

We will close this issue and wait for your feedback.

**Comment by mzealey** [comment]
Thanks for the information. However the main issue is that I see no way currently in the template to change the config to disable this option from being shown to users - can this be patched?

**Comment by FrederickBor** [comment]
Thanks for you feedback.

Sunstone does not provide customization at this level of detail. The "instantiate as persistent" option is a special case since it can over populate the VM Template catalog
