### ISSUE TITLE
Make VNTemplates compatible with vCenter network creation hook

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#4119]
**Description**
vCenter network creation hook is triggered when a vnet is allocated. This network allocate action should be triggered by the instantiate action. 

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Since there is currently a difference between allocate and instantiate, related to the VN template that reaches the hook (it only comes in the allocate API call, and not the instantiate), we are keeping the hook call to oned. Reasoning behind this is vnet creation or instantiation is not that frequent an operation, and is better to keep the code (both oned and hook) simple.

**Comment by mouyaq** [comment]
First, the create network hook must be registered for "one.vntemplate.instantiate" API call.
Second, network name should be taken from attribute NAME instead BRIDGE. As BRIDGE are using as network name, working with network templates, only the first network can be created, because the next ones have duplicate names.

**Comment by mouyaq** [comment]
https://github.com/OpenNebula/one/pull/4465
