### ISSUE TITLE
Unable to parse oned.conf: undefined method `chomp' for true:TrueClass

### ISSUE THREAD

**Issue by paleozogt** [OpenNebula/one#4937]
**Description**
I'm upgrading from 5.10 to 5.12 and seeing onedb fall down:

```
sudo onedb upgrade -v           
Unable to parse oned.conf: undefined method `chomp' for true:TrueClass
```

As a test, I installed 5.12 from scratch on another machine and ran `onedb upgrade` to see what would happen.  It fails with the same error!

In both cases I'm using the same oned.conf (the default with minimal modifications for mysql).

**To Reproduce**

Install 5.12 and run `onedb upgrade -v`.

**Expected behavior**

onedb needs to print out a more meaningful message, since there's nothing wrong with onedb.conf.

**Details**
 - Affected Component: onedb
 - Hypervisor: kvm
 - Version: 5.12.0
 - OS: Ubuntu 18.04

**Comment by meier-rene** [comment]
I had the same issue, also on 18.04. I could work around this issue by using onedb with options -u -p and -d.

**Comment by al3xhh** [comment]
Hello @paleozogt 

There was a bug in the documentation, the right command needs to specify the connection parameters. Run the command `onedb upgrade` with all the connections parameters, for example for MySQL:

```
onedb upgrade -v -S localhost -u oneadmin -p oneadmin -d opennebula
```

This has been fixed in the official [documentation](http://docs.opennebula.io/5.12/intro_release_notes/upgrades/upgrading_single.html#step-7-upgrade-the-database-version) already:
