### ISSUE TITLE
Allow migration to the same DS

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5132]
**Description**
When a VM have disks in different datastores it would be useful lo allow VM migration to the same DS to consolidate the disks location in the same datastore.

**Use case**
Having a VM with two disks as below:

   - Disk1: Datastore A
   - Disk2: Datastore B

It would be useful to allow to migrate VM to DS A to have:

   - Disk1: Datastore A
   - Disk2: Datastore A

**Additional Context**
It's already possible to migrate the VM to a third DS C having:

   - Disk1: Datastore C
   - Disk2: Datastore C

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
We've evaluated this carefully. This is a use case that is specific for vCenter, and unfortunately doesn't fit in the state machine that currently implements oned. In order to avoid overcomplicating this state machine with a corner use case (we would need also to forbid this operation for other hypervisors to avoid also overcomplicating the drivers) we won't be implementing this going forward.
