### ISSUE TITLE
Sunstone locked VMs show errors on tabs with graphs

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5200]
**Description**
If VM is locked, every time a VM tab with monitoring details is accessed in the Susntone, it generates monitoring API error which is propagated to the end user. See:

![image](https://user-images.githubusercontent.com/414850/101817930-70f60e80-3b23-11eb-8af7-86b3b0469ad7.png)

**To Reproduce**
- Start a VM
- Lock VM
- Open VM details
- Click on Capacity/Storage/Network tab

**Expected behavior**

1. It doesn't show error to the users.
2. It shows monitoring data.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12.6

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment]
Fixed with [e1ea0b79681fba667b6c110e0be260f3e3b35f6b](https://github.com/OpenNebula/one/commit/e1ea0b79681fba667b6c110e0be260f3e3b35f6b) and [ab260f6395375de80353c8e0e66e6524dbeb42e6](https://github.com/OpenNebula/one/commit/ab260f6395375de80353c8e0e66e6524dbeb42e6) 

Also found an error in master with lock and unlock.
PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/813)
- [Docs](https://github.com/OpenNebula/docs/pull/1474)
