### ISSUE TITLE
onegate vm update breaks with "="

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5240]
**Description**

Due to this Updating a VM template via onegate using bse64 values is error prone

**To Reproduce**

onegate vm update --data SSHHOSTKEY_RSA="$(cat /etc/ssh/ssh_host_rsa_key.pub)"

**Expected behavior**

Update VM to work

**Details**
 - Affected Component: OneGate
 - Hypervisor: -
 - Version: development

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by flohoff** [comment]
An alternative would be to base64 encode the content:

onegate vm update --data SSHHOSTKEY_RSA="$(cat /etc/ssh/ssh_host_rsa_key.pub | base64)"

The problem here is base64 padding which may produce "=" at the end which onegate refuses. This seems to work in the context with the startscript and the like.

Workaround for me is to replace "=" with "-" with tr as "-" is a char not used by base64

onegate vm update --data SSHHOSTKEY_RSA="$(cat /etc/ssh/ssh_host_rsa_key.pub | base64 | tr '=' '-')"

But it would be really nice to be able to put any string in there as long as its a "single line".

**Comment by al3xhh** [comment]
PRs to merge in master:

- [code](https://github.com/OpenNebula/one-ee/pull/961)
- [docs](https://github.com/OpenNebula/docs/pull/1512)
