### ISSUE TITLE
Option to create a raw volatile disk without creating a filesystem (backward compatibility?)

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5282]
**Description**
It looks like the option to create a disk image with a filesystem was restored (in 6.0-beta) but via a different variable and this time, there is no option to create a raw disk as in up to one-5.12.
![image](https://user-images.githubusercontent.com/11386997/110337284-6a960680-802e-11eb-9ca5-8e097e47c6d2.png)

**Use case**
Backward compatibility, same user experience, etc.

**Interface Changes**
Volatile disks: add an option to select RAW disk beside (FS, swap)

**Additional Context**
As a workaround, I've found that if I define non-existent fs like '_None_' it could work in some cases.
![image](https://user-images.githubusercontent.com/11386997/110338148-5acaf200-802f-11eb-9212-7c8a4e919a18.png)

So not sure what is better, define type raw or define an option to have None...

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment]
Hi @atodorov-storpool, this have been already fixed in the development branch. By default the Filesystem field should be empty from now on (check image attached). Thank you very much for your feedback!!

![attach_unformat_volatile_disk](https://user-images.githubusercontent.com/19222136/110460908-168f2e80-80cf-11eb-86d2-62a77337064f.png)
