### ISSUE TITLE
Install One CLI Tools on Mac OS

### ISSUE THREAD

**Issue by Th0masL** [OpenNebula/one#5483]
**Description**
It would be great to be able to install the CLI Tools on Mac OS.

**Use case**
I want to use some of the CLI binaries to execute API calls against the OpenNebula API.
I'm using a Mac laptop and it's annoying to have to connect to a Linux machine in order to be able to use the CLI Tools.

**Changes**
Is there a way to build the CLI Tools only, from source, on Mac OS ?
I saw that the CLI binaries were ruby code/gems, so I think it should be doable.
If so, could someone update the documentation to explain how to install it ?
If it's not possible yet to install those on Mac OS, how complicated would that be to implement such functionality ?

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
The whole CLI is written in Ruby, you just need to do the following:

- Install Ruby.
- Install all the dependencies gems.
- Install the CLI code and the configuration files.
- Run the commands against the OpenNebula instance running in a different server using `--endpoint` parameter.

Closing this.

**Comment by danhigham** [comment]
@al3xhh The install script (install.sh), in it's current state, does not work on Mac OS due to a subtle difference in the way "cp" works on linux and Mac OS, see my PR for a fix (https://github.com/OpenNebula/one/pull/5136)

There are also three dependencies that have to be installed to satisfy some gems with native extensions (augeas, postgresql and mysql), these should also be installed using homebrew first before installing the gems. It also might be worth pointing out that the version of Ruby that ships with Mac OS will not suffice due to dependencies on openssl, a better path would be to install stable Ruby 2.7 with rbenv first. I would like to contribute to the documentation for installing the CLI on Mac, where would be the best place to do this?
