### ISSUE TITLE
Predict service's resource consumption and prevent VM deployment if quotas are exceeded

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#5729]
**Description**
When OpenNebula user is about to hit [quota limits](https://docs.opennebula.io/6.2/management_and_operations/capacity_planning/quotas.html), but deploys an OneFlow service anyway, the deployment will be executed and will fail.
The new feature would be to predict the failure, prevent deployment and inform the user, that it's not possible to complete the request.

**Use case**
It's for preventing execution of unnecessary deployments, it can be annoying to the end user.

**Interface Changes**
Sunstone should display an error and optionally a dialog box to force execution of the operation anyway.
API should return appropriate error message and should have an input option to force the deployment.

**Additional Context**
N/A

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment]
The implementation of this issue it is quite complicated because oned controls quotas and there is no "flow" objects in oned. And flow, that deals with flows does not have quotas; that will require reimplementing all the system in the upper layer.

We are closing this one as the effect is limited and will require just minimal user interaction on failure
