### ISSUE TITLE
Make Wild VM image import optional

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5781]
**Description**

Related to #5756, some situations (ie, migrating a wild VM) causes the imported images to be left in the original datastore in OpenNebula, which is not convenient if you want for instance to delete the datastore.

In this situations, if known beforehand, it may be useful to avoid OpenNebula creating images on import. We can do a first implementation based on a vcenterrc setting.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment]
After evaluating the issue, we have seen that the image creation is needed in order to be able to have the VM running in OpenNebula. We have checked the migration between different datastores and all the information is persisted without any issue.

We have added a note in the documentation, to warn users when performing a migration between datastores.

**Comment by tinova** [comment]
Added note in doc: https://github.com/OpenNebula/docs/pull/2213
