### ISSUE TITLE
Sunstone to allow disk size and resize up to the max free storage

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5837]
**Description**

Sunstone currently does not implement any check for disk size. It is possible to set values that will set a VM in pending state indefinitely.

**Interface Changes**

Disk size fields should check for the maximum value possible and refuse if this is exceeded.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by atodorov-storpool** [comment]
IMO such restrictions should be implemented on the core/API level and should take into account the capability of the storage backend of the datastore(defined, declared in the datastore configuration...)? This way it will natively work for CLI, Fireedge, Sunstone or other parties like external billing without the need of keeping the different implementations in sync?

So, following the original description
> Sunstone currently does not implement any check for disk size. It is possible to set values that will set a VM in pending state indefinitely.

Such implementation will return the error on the API level and Sunstone, Fireedge, and CLI should just handle communicating with the operator(the admin) a propper error response instead.

Writing that because a datastore with thin-provisioned storage could support an image with a size, bigger than the current available on-disk size (at the time of the creation of the image).

**Comment by rsmontero** [comment]
Just a quick note to prevent any misunderstanding. All the checks referred here are already done by the oned core, and are available at the API level.

This issue is to provide some guidelines **prior** to making any API call. OPenNebula already validates datastore capacity, and user quotas on API requests or VM deployment. In fact there are specific driver actions so drivers provide this image sizes or how the sizes should be computed etc...

**Comment by jkhongusc** [comment]
This issue doesnt really address what we (USC) initially requested.  What we would like is a way to control (customizable) disk capacity within the VM template similarly to CPU, MEMORY, and VCPU.  Why can we not have a "DISK" attribute?

CPU    = "1"
MEMORY = "2048"
VCPU   = "2"
USER_INPUTS = [
  VCPU   = "O|fixed|| |2"
  CPU    = "M|list||0.5,1,2,4|1",
  MEMORY = "M|range||512..8192|2048" ]

https://docs.opennebula.io/6.2/management_and_operations/vm_management/vm_templates.html#preparing-vm-templates-for-end-users
