### ISSUE TITLE
Sunstone error on vCenter VM without ESX location

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5851]
**Description**

When a vCenter VM is not monitorized yet, the error in the log is

```
06 HTTP/1.1" 200 - 0.1728
Wed May 25 07:55:42 2022 [E]: Could not determine the vCenter ESX host where
             the VM is running. Wait till the VCENTER_ESX_HOST attribute is
             retrieved once the host has been monitored
```

However, in the front-end the error message reads:

`It appears there was a server exception. Please check server's log.`

**Details**
 - Affected Component: Sunstone
 - Hypervisor: vCenter
 - Version: 6.4 and master

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
@tinova PRs to be approved:
- Code: https://github.com/OpenNebula/one-ee/pull/2105
- Docs: https://github.com/OpenNebula/docs/pull/2295

**Comment by ortizjoseluis** [comment]
Good morning community.

I have recently updated the version of my Vcenter to 7.0.3p

Since the update, the VMRC cannot start in OpenNebula as I get the same error

“Could not determine the vCenter ESX host where the VM is running. Wait until the VCENTER_ESX_HOST attribute is retrieved once the host has been monitored”

Can someone help me with this error?

Thank you very much in advance

**Comment by tinova** [comment]
please check your host is correctly monitored, and check /var/log/one for errors in monitoring
