### ISSUE TITLE
Deleted attribute came back after reboot of one host of the cluster

### ISSUE THREAD

**Issue by Th0masL** [OpenNebula/one#5910]
**Description**
One of the attributes I deleted months ago from a `Virtual Network` came back after one of the Physical Hosts rebooted for the first time since this attribute change.

**To Reproduce**
Sadly I have no idea how to reproduce this bug.

**Expected behavior**
The changes should be persistent, obviously 😄 

**Details**
 - Affected Component: Sunstone
 - Hypervisor: kvm
 - Version: 6.0.0.2

**Additional context**

I originally setup the cluster 1 year ago, and because I use both a Public Network (eth0) and a Private Network (eth1), I deleted the `GATEWAY` attribute from the Private Network to ensure that the only `ETHx_GATEWAY` Context Variable visible on the VMs is the Gateway of the Public Network.

This week I restarted a Physical Host that seems to have never restarted before the original installation of OpenNebula 1 year ago.

After the restart, the `GATEWAY` attribute that I originally deleted from the Private Network came back, and therefore any VM being created after the reboot of this Physical Host were seeing an additional `ETH1_GATEWAY` Context Variable, breaking the `addon-context-linux` initialization script behavior.

I've also opened an issue in the addon-context-linux repo to [improve Default Gateway selection when dual NICs #274](https://github.com/OpenNebula/addon-context-linux/issues/274). 

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
Hi @Th0masL ,

There should not be any relationship between hypervisor restart and VM metadata. I think that probably what it happened is that you updated the network, but those changes are not propagated to the NIC so the CONTEXT kept the previous GATEWAY, so after restarting the VM (because of the host restarted) the old value showed up. 

You can check (e.g. with onevm show -j) if the NIC includes the old GATEWAY value...
