### ISSUE TITLE
IP spoofing not working when IPv6 with prefix

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5971]
**Description**
IPv6 is almost like IPv4 but not precisely. With IPv6, a prefix length defines the address range. Usually, IPv6/64 is assigned as the smallest routable address.

**To Reproduce**
Define AR with one IPv6 /48 prefix length (size 1, PREFIX_LENGTH=48)
Assign to VM NIC with IP spoofing enabled
Nothing than IPv6/128 is working because of the created rules.

**Expected behavior**
All assigned IPv6/prefix should work.

**Details**
 - Affected Component: [Networking]
 - Hypervisor: [KVM]
 - Version: [ALL]

**Additional context**
A patch is on the way.

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
Hi @atodorov-storpool 

IPv4 and IPv6 are the same, prefix is the relevant part for routing. The IP spoofing rule needs to consider the full /32 /128, unless you are dealing with a router or a VM that needs to manage the whole range

* If the VM is not a router current IP spoofing rule works, and prevent the VM for using an unicast IP different from the assigned one
* if the VM is a router or needs to generate full /64 /48 or whatever blocks then IP spoofing needs to be disabled

We can think of adding a new "network spoofing" filter, but as far as I see the code it is working as expected.

Note that we already include the link-local addresses and multicast addresses for nbd, router discovery, solicited node etc...

**Comment by atodorov-storpool** [comment]
Hi @rsmontero 

I see.

So, the current ip spoofing implementation is limited to 2^16 addresses per NIC? For Ipv4 it is enormous, but for ipv6 it is just /112. Maybe worth noting as a known IP spoofing limitation?

Also, reading the code, I was wondering why there is inconsistency in the variable's names. I mean the IP6_PREFIX_LENGTH in the context is the PREFIX_LENGTH in the AR record.

And a side note, how to propagate a custom variable defined in an AR to be available in contextualization and VM metadata[*]? It looks like INHERIT_VNET_ATTR is propagating only VNET/TEMPLATE/* but not AR/* variables...

[*] I am always confusing the VM Template for instantiating with the VM template of the running VM, so by "VM metadata" I am addressing the template of the running VM.

**Comment by rsmontero** [comment]
IP spoofing is a mechanism to enforce that only the IP address assigned to a NIC is used as source IP in a IP datagram. It has nothing to do with protocol version or network prefix length.

In the OpenNebula drivers we simply add rules like:
```
   #   IP spoofing
    #   iptables -A one-3-0-o ! --source 10.0.0.1 -j DROP
```
with the exception mentioned above, and considering alias etc...

So the problem may arise when more IPs than those assigned by OpenNebula needs to be used by the VM. This is a valid use case and something we need to address at the VNET level, to properly model for example reverse proxy's routers etc..

The inconsistency is probably because they are for oned and context_packages. In context, every IP6 parameter is `IP6_something` (except  IP that is IP6 an not IP6_IP)

About inherit yes INHERIT_VNET_ATTR should work, it should appear in the NIC. I did not test it manually, but maybe if you can verify it is not working for you, we need a separate issue

**Comment by atodorov-storpool** [comment]
The default value for the _maxlength_ of the created ipset is 65536:
https://github.com/OpenNebula/one/blob/master/src/vnm_mad/remotes/lib/security_groups_iptables.rb#L523

I was trying to inherit AR/TEST_VARIABLE for example, but it is working with the name only (TEST_VARIABLE).
The value is in the VM metadata, but is missing in the contextualization, though. But that is probably the expected behaviour.
Tested the precedence too - the same variable in the AR overrides the one in the VMNET template, as expected.
So what and when to be copied to context is another matter :)

I'll check with the customer does it need spoofing protection enabled and will patch the code if needed.

I am closing the ticket
