### ISSUE TITLE
QoL improvements for ERROR Dismiss popup

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6069]
**Description**
Allow a way to improve the DISMISS click on Sunstone after an error occurs. The goal is to avoid manually clicking dismiss on VMs after the error is no longer relevant. The relevancy is the tricky part.

This is just a cosmetic feature as it doesn't affect operations at all, just admin eyes.

**Use case**
Ease of management in case the same error affects a batch of VMs. Save time for each VM click

**Interface Changes**

Proposed alternatives
- disable the last error pop up after X amount of time  by removing the VM Template ERROR attribute
- disable pop ups entirely as another setting
- provide a global Dismiss button in the vm pool view

**Additional Context**
The popup is a consequence of Sunstone detecting the ERROR attribute on the VM Template. Removing the attribute is what the dismiss button clicking does. Having a global button is potentially bad way of dealing with this case as it will issue a vm_pool update which affects every VM.

If this is implemented it will only apply to the new FireEdge Sunstone

## Progress Status
- [x] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by madmax01** [comment]
Just wanted to say

"provide a global Dismiss button in the vm pool view"

instead of fully "Global".... would be helpfully just "dismiss button"  - but depending on vms choosen.

example: 100 vms.. 10 of them got issues... Admin fixed it... Admin would then check box all 10vms and click "dismiss".. so not whole VM pool affected....

or if its overnight anyway and may no admin online > then per other Point frontend dismiss by itself all invalid errors.

great option ;)
