### ISSUE TITLE
Evaluate cppcheck (static analysis tool)

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#6103]

**Comment by paczerny** [comment]
Bugs discovered by CppCheck (fixed)
* Minor memory leak
* Possible oned crash due to wrong pointer handling
* Delete private Marketplace only if it's empty
* Wrong response in case of bad group quota

Commits:
* [Add CppCheck to smoke tests](https://github.com/OpenNebula/one-ee/commit/a5c57b69b37ffae93468127021ea953e1498aaea)

PRs:
* [src](https://github.com/OpenNebula/one-ee/pull/2477)
